grafana:
  enabled: false

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 2d

    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

    serviceMonitorNamespaceSelector: {}

    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}

    ruleNamespaceSelector: {}

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi