architecture: standalone

auth:
  username: qvs
  database: qvs
  existingSecret: qvs-postgresql-credentials
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

volumePermissions:
  enabled: true
  containerSecurityContext:
    runAsUser: 0

metrics:
  enabled: true

  image:
    registry: registry-1.docker.io
    repository: bitnami/postgres-exporter
    tag: ""
    digest: "sha256:53ab72a1b940d7637e91619f1000da9ebef14bc7dad74321a78731d65c79f55b"

  service:
    ports:
      metrics: 9187

  serviceMonitor:
    enabled: true
    namespace: qvs-app