architecture: standalone

auth:
  username: qvs
  database: qvs
  existingSecret: qvs-postgresql-credentials
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

volumePermissions:
  enabled: true
  containerSecurityContext:
    runAsUser: 0

metrics:
  enabled: false