apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgresql
  namespace: qvs-app
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: qoves-postgresql
      app.kubernetes.io/name: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5432
