apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qvs-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/eferoghenej/qvs.git
    targetRevision: HEAD
    path: network-policies

  destination:
    server: https://kubernetes.default.svc
    namespace: qvs-app

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true