---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qvs-postgresql-credentials
  namespace: qvs-app
spec:
  encryptedData:
    password: AgCY52jOol7YB16hrTEbu3ZVqiso40YX5emE5n9MNNhCiE9roVEmS4kYd0aKtcsif+f1aRsc/DVv+J5io0Exm+V4orrsFFHkPQeb8Gs5mAI7ncVdMrYWma1IB75CQcPg31JJg/o5+AJfajBta1SpT/OioGsv6jAvSiDUDdZBcEGjoAP+a+m9ikxwm303euJkK+GNNIn00+PSKER0YpMyAYaOBXZe/q9Szdk/aqAPOGmoF+6oYVh4SYvDccRSBQ0fDU4XG7oq7otJNutK5xU6uNkowyapJEvrJjC59gWJaTF1fX+hHq/nlOTmxMNpJnPjeKURsjOeJN0tDnagFIH/VNAmvzse7+Z3wyI90DOuVOZK/mAaqqXNhKzOahebgBbq3tNHxB5ZGvMStpne3o/UTEHmIliNTwIk4xR2F2SsNpulFLsDNVYvOxtARpGwMSDt97uuk53yUSgujyT03SiUHePm370UOzzWG0bX8ohvAfT4rXm1Jt+w4hwvs5Dui8AJEejozit9cDa7FP3QA/O5xxnYEQvvJFs9dnq/GdyEt2+l3Aon1Gtk1nwrbUHg7yItvN/yjyj28/UtjyiFwlJYUi3KaBM1Yw5voMjAoK47vtHWP6a52gYKO36tnwGs4KxYvAUcFEVJXaBk+Iz5gO2ehwkF4izPtnm0Rbrv39SiP0Crju8UxlH3JjOXMqOuQ/4K2NkQVdENdvMRUVHVA+QN25QeBolwJy4ZuqAPbG1uf4fMEw==
    postgres-password: AgBnmtLK6LqaP5gMnyJUOByQewwJ0IbxtAGQ8Y62uTPYjvJrwvUrjzQuf3qnmjkUhf7r+8C50odikBDVIBlpOrlGZZ5GViqAq3KefM0mDzTDVrLY+XWCuMo4CcQxbhHI2RIU57JZ4B7iCsrnJeGCW+J7MxYJt/vgqHa6US1zaeh5KhElYwwoHs3yevaIRndKoXoqH9C0VbQD1EIN1YkRlLTgrkcGjcTyQiRnVfDIWXsyIQZMJULdsDQzzRYuFCMW3g9gkLfMIIn3/bMsHfz4ReoU/7E12CNARgpN7++gJe84GbWIVCKdayZ/6uoYLiKgSjvYwCLLq7TSMFRXUOFrK1r1jtKcnloPUBn3xWRs1ACgcuBhsHBImzX7DUrNMV2IG5RqzEl9denW3fpLh5ZKKiuqszy0Mdt/LLUzTFQ1es1CCL+bdYHD1/4nbrEWwIBvHu6uKTghP3RFLWhx42tbC6Le63O/GjKykTCvbOenbRAYrKEeRuXIR4aHRj/pbrf+jiNTxaWrKu2ZGZySeEYggTN3YogcN0fWC90226e/6WppgNEvr/JRnRhdP+0I/1EeO0xvxpRH3mkVXYzzZ/UPmZ2AIecQHiGk8bx1I2VthycBrwiWgdrrhHXdrx5ondVAyezH2GKXUuRjrro0Y/HImykHjxdUnFrOD/Biyo8SiqLLviJoQQ01CLFE+cFBqz+7IL0bvAaxIEhasaJJNB76ciI02wsi1orRKJXS8iN6h7jQCA==
  template:
    metadata:
      name: qvs-postgresql-credentials
      namespace: qvs-app
    type: Opaque
