---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qvs-postgresql-credentials
  namespace: qvs-app
spec:
  encryptedData:
    password: AgAWtxsBbp6lhxLXqe3XKCQsuTppHHPUiD8mtgqhCb7wHXrJEQkqb1yX95YOLWV212SyINH0zzLwwU8XuTtqMosTiu0zc4CyusEDyRj1TZ+FAUV9NDN7a+grssRRO1LIKVGuQn8G7f+P1XkCUfbDv0eOET1/BanxnsVlkNBxwsZELENroVI6JJwe6gCGMpksEPqEJCZ5VSLmEAyuz/PQYMWLqCOdJ7w0NSxl/ln8+Qi43dhTXd7oGk7nqOwY0SB6uJ/hn2G13+9jgTM2mHvYZG0iAhK+lDcF54+EUz9SG3epLcnpTlOwErSpizQJclGO435pfU/fV8QFbF5lwPdYoiHhYuwm75bS0OESDzERfEvglGnPL2rjwv2pfwfyrXN5J3SeuZJFCsz6NW4BEpXypht6OkPuDFiunP0bDEUxQxbgyWRs5MqXVSJ0LyrA32BroaZQvyv3CqiqZtZydIW3s2GsmQbFPWQxTWhmSFHG88J9UgQ/KksI9C/ho53ta11oJskIm1NiNMYHtoEgHo4mtgPOhkDgFTMwmEcID8Ujo9TIbSIfuluEo3YZfOgsgZG1lrzyQcN3wN8XPK+r68p/3B0Gc95poyrt67njb922n4AcbdQuc1QAPpv0AYxTO2y7Hn4Pn8nDF0U6YD9Xq1kRKhCJZAuqTqDi6uE+JI9MC6zmshA9BHpeXCz88TRxjifEOCmdIrO1repl5A==
    postgres-password: AgBF5H4qHXdOjNvcokYVE5Qgy6BCjFqj69xfy80NkHJdKuz9F5DquO0UJn/xxr2ZBKcZoYTW4JNzFViio5wfaFtpabLlm5qLi+3vrbxf6IcuFCwkvfl4ooF5TXnL1KvstGn9xd2dNb3ofa5cfHU+o3MY3xR7Rw3PL8iUhxJUHKTXC61wTf91/+5vmN62HzvYtYx1Lj/ipb5EA+XlWLhRhEFjwEPFkdYcuY/0SCGM5Jbv5QKbni7GqH0NttFujeJiKlpntecY8nEQdYMlqbSAudg1oRz3kbot5XnrDYA1veMHIYbEbZXAEwTfKjm3NA6StKvOKV+sskC2xNOLdEcbVeqGpYheg0IK0u3ya9iStX5CwDQp50a/ci4EaPsVHPRVQtWwhxNHPLnxLdt4JMQP16b4MadG5wH/43Ab39P5q59Z0cGqfsp4wgJOxtw8nQuA/fHgm11L5Eb06w420VCqPfuWjWQiwILtCLZg6n+eDi1LhKfd2Jlckyj5zxkS5S2G+JsUL+slLRlND0nUV8WqcY5+dOyreZHM26YYX0090kglEz1OSDOyavLkRxps4uH0lj28I3xkG6GiMK2HNhJiXAgke7hhfkDMoi1fmo9hn1gQh8w0u6p8WtKSWIhAG7gnvj4bI8QHRXx+tHI+kpD3UyJDfi3+GT2um4wnrCdiyXk/5jytVXh3xj3VaGhLKzhACleIA03nGNvL0g==
  template:
    metadata:
      name: qvs-postgresql-credentials
      namespace: qvs-app
    type: Opaque
